# Markdownlint configuration for Fascinante Digital Infrastructure
# This file configures markdownlint rules for consistent documentation

# Enable all rules by default
default: true

# Disable specific rules
MD013: false  # Line length
MD033: false  # Inline HTML
MD041: false  # First line should be a top level heading
MD024: false  # Multiple headers with the same content
MD029: false  # Ordered list item prefix
MD030: false  # Spaces after list markers
MD026: false  # Trailing punctuation in header
MD036: false  # Emphasis used instead of a header
MD002: false  # First header should be a top level header
MD012: false  # Multiple consecutive blank lines
MD025: false  # Multiple top level headers in the same document
MD022: false  # Headers should be surrounded by blank lines
MD032: false  # Lists should be surrounded by blank lines
MD031: false  # Fenced code blocks should be surrounded by blank lines
MD040: false  # Fenced code blocks should have a language specified
MD046: false  # Code block style
MD048: false  # Code fence style
MD049: false  # Emphasis style should be consistent
MD050: false  # Strong style should be consistent
