# Pre-commit configuration for Fascinante Digital Infrastructure
# This file configures pre-commit hooks for code quality and security

repos:
  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
        args:
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_tflint
        args:
          - --args=--config=../../tools/.tflint.hcl
      - id: terraform_tfsec
        args:
          - --args=--config-file=../../tools/tfsec-excludes.yml

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args:
          - --unsafe
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=1000
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args:
          - --fix=lf

  # Security hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args:
          - --baseline=.secrets.baseline
          - --exclude-files=secrets/.*\.tfvars$

  # Documentation hooks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args:
          - --config=.markdownlint.yaml

  # YAML hooks
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args:
          - --config-file=.yamllint

  # Shell hooks
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck

  # Python hooks (for scripts)
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=88
          - --extend-ignore=E203,W503

# Configuration
default_language_version:
  python: python3

# Exclude patterns
exclude: |
  (?x)^(
    \.git/.*|
    \.terraform/.*|
    \.pre-commit/.*|
    .*\.lock$
    .*\.tfstate.*$
  )$
