services:
  tf:
    build: .
    working_dir: /workspace/envs/dev
    volumes:
      - ./:/workspace
      - ${HOME}/.aws:/root/.aws:ro
    env_file:
      - .env
    environment:
      - AWS_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
    stdin_open: true
    tty: true
