name: plan-dev-opentofu
on:
  pull_request:
    branches: [main]
    paths:
      - "envs/dev/**"
      - ".github/workflows/plan-dev-opentofu.yml"

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # SÚPER-ÉLITE: OpenTofu setup con mejores prácticas 2025
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.10.6
          tofu_arch: amd64

      - name: Setup Node.js (para herramientas modernas)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Cache OpenTofu
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugins
            ~/.opentofu.d/plugins
          key: ${{ runner.os }}-opentofu-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            ${{ runner.os }}-opentofu-

      - name: Cargar secrets
        run: |
          echo "AWS_REGION=us-east-1" >> $GITHUB_ENV
          echo "TF_VAR_environment=dev" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: envs/dev
        run: |
          tofu init -input=false -upgrade

      - name: Terraform Plan
        working-directory: envs/dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
          CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        run: |
          tofu plan -compact-warnings -no-color -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: envs/dev/tfplan
          retention-days: 7
