name: Terraform Plan (1Password)
on:
  workflow_dispatch:
  push: { branches: [main] }
jobs:
  plan:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.ONEPASSWORD_SERVICE_ACCOUNT_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: 1password/install-cli-action@v1
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.9.5 }
      - name: Init
        run: op run --env-file=<(source scripts/export-env-1password.sh) -- terraform init -upgrade
      - name: Plan
        run: op run --env-file=<(source scripts/export-env-1password.sh) -- terraform plan -no-color
